# Generated by Django 3.0.6 on 2020-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marauders_map_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
